### ISSUE TITLE
《ROS机器人开发实践》阅读过程发现的疑似笔误

### ISSUE THREAD

**Issue by WXLmjr** [huchunxu/ros_exploring#1]
原书16页
2.3.2小节 元功能包
语句——“此外，元功能包清单不需要<buildtool_depend>标签声明编译过程依赖的其他功能包”  其中<buildtool_depend>是否应该写为：<build_depend> ?

**Comment by huchunxu** [comment]
多谢，此处确实笔误，第二版印刷中会修正
