### ISSUE TITLE
gazebo 加载world时特别慢

### ISSUE THREAD

**Issue by lvhualong** [huchunxu/ros_exploring#11]
古月老师，还有一个问题就是，在我使用Gazebo做机器人仿真的时候， 当我在world文件上添加几个模型和物体的时，然后启动gazabe, 常常出现gazebo world加载不出来的情况，然后我的CPU GPU还有内存都还有很大余量，不知为什么world为何加载不出来。请问这种情况，有改进或者加速的办法吗

> 

![screenshot from 2019-01-14 19-15-28](https://user-images.githubusercontent.com/26672004/51109669-d9052280-1830-11e9-909d-fe215a2a5c55.png)

![screenshot from 2019-01-14 19-16-25](https://user-images.githubusercontent.com/26672004/51109701-ede1b600-1830-11e9-85e0-c18325e0c202.png)

**Comment by huchunxu** [comment]
> 古月老师，还有一个问题就是，在我使用Gazebo做机器人仿真的时候， 当我在world文件上添加几个模型和物体的时，然后启动gazabe, 常常出现gazebo world加载不出来的情况，然后我的CPU GPU还有内存都还有很大余量，不知为什么world为何加载不出来。请问这种情况，有改进或者加速的办法吗
> 
> > 
> 
> ![screenshot from 2019-01-14 19-15-28](https://user-images.githubusercontent.com/26672004/51109669-d9052280-1830-11e9-909d-fe215a2a5c55.png)
> 
> ![screenshot from 2019-01-14 19-16-25](https://user-images.githubusercontent.com/26672004/51109701-ede1b600-1830-11e9-85e0-c18325e0c202.png)

这个是gazebo软件本身的问题，我也不清楚，建议google找下
