### ISSUE TITLE
Error in mrobot_navigation when roslaunch move_base.launch 

### ISSUE THREAD

**Issue by weiranfu** [huchunxu/ros_exploring#13]
i try to roslaunch mrobot_navigation fake_nav_cloister_demo.launch, and then it doesn't work:
the terminal says that >>

Warning: Invalid argument "/map" passed to canTransform argument target_frame in tf2 frame_ids cannot start with a '/' like: 
         at line 134 in /tmp/binarydeb/ros-melodic-tf2-0.6.3/src/buffer_core.cpp
 i set up the navigation goal, but the car didn't move...

And i found the solution on the internet: https://github.com/ros-planning/navigation/issues/794

solve it by removing the "/" in global_costmap_params.yaml and local_costmap_params.yaml

finally, it works.

**Comment by huchunxu** [comment]
Thanks for the solution. I have not tested code with ROS melodic.
