### ISSUE TITLE
Error in the mrobot_gazebo

### ISSUE THREAD

**Issue by zxfever** [huchunxu/ros_exploring#14]
Hello
when i run your code in `mrobot_gazebo` 
`roslaunch mrobot_gazebo view_mrobot_with_camera_gazebo.launch` it works well and i can control it via the `mrobot_teleop.launch`. But when i run the `rqt_image_view`.The gazebo has the error:

gzserver: /build/ogre-1.9-mqY1wq/ogre-1.9-1.9.0+dfsg1/OgreMain/src/OgreRenderSystem.cpp:546: virtual void Ogre::RenderSystem::setDepthBufferFor(Ogre::RenderTarget*): Assertion `bAttached && "A new DepthBuffer for a RenderTarget was created, but after creation" "it says it's incompatible with that RT"' failed.
Aborted (core dumped)
[gazebo-1] process has died [pid 332, exit code 134, cmd /opt/ros/kinetic/lib/gazebo_ros/gzserver -e ode /home/zxf/my_was/src/mrobot_gazebo/worlds/playground.world __name:=gazebo __log:=/home/zxf/.ros/log/c198788e-61de-11e9-86e1-7c2a31503f61/gazebo-1.log].
log file: /home/zxf/.ros/log/c198788e-61de-11e9-86e1-7c2a31503f61/gazebo-1*.log

could you give me some advice? thanks a lot!

**Comment by huchunxu** [comment]
Please refer to：
https://github.com/uzh-rpg/rpg_quadrotor_control/issues/58
https://github.com/udacity/RoboND-Perception-Exercises/issues/4
