### ISSUE TITLE
MoveIt机械臂控制章节运行代码出错

### ISSUE THREAD

**Issue by tfwang08** [huchunxu/ros_exploring#16]
在MoveIt!编程学习章节中运行代码都出现了类似的错误，以关节空间规划为例：
运行rosrun marm_planning moveit_fk_demo.py命令后，机械臂没有运动，运行launch文件的终端输出为：

You can start planning now!

[ INFO] [1562576474.274474940]: Combined planning and execution request received for MoveGroup action. Forwarding to planning and execution pipeline.
[ INFO] [1562576474.274891116]: Goal constraints are already satisfied. No need to plan or execute any motions
[ INFO] [1562576476.354635249]: Combined planning and execution request received for MoveGroup action. Forwarding to planning and execution pipeline.
[ INFO] [1562576476.354985038]: Planning attempt 1 of at most 1
[ INFO] [1562576476.357638285]: Planner configuration 'gripper' will use planner 'geometric::RRTConnect'. Additional configuration parameters will be set when the planner is constructed.
[ INFO] [1562576476.358687775]: RRTConnect: Starting planning with 1 states already in datastructure
[ INFO] [1562576476.369870458]: RRTConnect: Created 4 states (2 start + 2 goal)
[ INFO] [1562576476.369955176]: Solution found in 0.011544 seconds
[ INFO] [1562576476.373558468]: SimpleSetup: Path simplification took 0.003387 seconds and changed from 3 to 2 states
[ INFO] [1562576476.904228113]: Completed trajectory execution with status SUCCEEDED ...
[ INFO] [1562576478.004197492]: Combined planning and execution request received for MoveGroup action. Forwarding to planning and execution pipeline.
[ INFO] [1562576478.004402229]: Planning attempt 1 of at most 1
[ INFO] [1562576478.005634270]: Planner configuration 'arm' will use planner 'geometric::RRTConnect'. Additional configuration parameters will be set when the planner is constructed.
[ INFO] [1562576478.006322077]: RRTConnect: Starting planning with 1 states already in datastructure
*** stack smashing detected ***: /opt/ros/kinetic/lib/moveit_ros_move_group/move_group terminated
[move_group-5] process has died [pid 3031, exit code -6, cmd /opt/ros/kinetic/lib/moveit_ros_move_group/move_group __name:=move_group __log:=/home/tfwang/.ros/log/e1019aec-a15e-11e9-a219-88b11175f2f1/move_group-5.log].
log file: /home/tfwang/.ros/log/e1019aec-a15e-11e9-a219-88b11175f2f1/move_group-5*.log

**Comment by Destinycjk** [comment]
您好，请问这个问题您是如何解决的？我也碰到了一模一样的问题。
