### ISSUE TITLE
在learing_tf中，启动launch文件后仿真器中只有一个乌龟

### ISSUE THREAD

**Issue by wbercode** [huchunxu/ros_exploring#17]
如题，在learning_tf中，启动launch后仿真器中只有一个乌龟，没有实现一只乌龟跟随另一只乌龟运动。
请古月居大佬百忙之中解惑，谢谢！

**Comment by huchunxu** [comment]
请检查是否关闭了所有ros节点及roscore，重新启动试下

**Comment by wbercode** [comment]
现在可以了，谢谢！之前我关了ros节点，可能没关roscore。
