### ISSUE TITLE
关于marm_gazebo中arm_gazebo_controller.launch文件作用的问题

### ISSUE THREAD

**Issue by JiamingXiao** [huchunxu/ros_exploring#20]
[arm_gazebo_controller.launch](https://github.com/huchunxu/ros_exploring/blob/master/robot_marm/marm_gazebo/launch/arm_gazebo_controller.launch) 文件似乎并没有被使用，请问这个文件是不需要的么？还是说忘记写在 bringup 的 launch 文件里了

**Comment by huchunxu** [comment]
arm_gazebo_control.launch调用了该文件，书中有例程使用的说明，请参考
