### ISSUE TITLE
有关于.rviz文件的作用问题

### ISSUE THREAD

**Issue by salvatoreitachi** [huchunxu/ros_exploring#23]
您好，在navigation仿真导航中，如果删除了rviz文件夹中已经跑出图并保存好的.rviz文件，则在roslaunch mrobot_navigation fake_nav_cloister_demo.launch时，rviz仿真界面中的displays就会只显示默认标签，没有map、odometry、inflated obstacles等书中实例结果所显示的标签。

**Comment by huchunxu** [comment]
当时是这样的，.rviz文件就是用来保存这些配置的，删除后需要重新配置

**Comment by salvatoreitachi** [comment]
感谢您的回复，但在我重新配置时，odometry EKF，inflated obstacles两个标签无法在displays的add中找到，请问这是什么问题呢

**Comment by huchunxu** [comment]
是添加odom这个的，然后命名并设置你的话题，并没有直接odometry EKF，inflated obstacles的选项
