### ISSUE TITLE
6.2.4运行launch文件报错[joint_state_publisher-2] process has died

### ISSUE THREAD

**Issue by hhxzzy** [huchunxu/ros_exploring#24]
古月老师你好，我的ubuntu版本是18.04，ros版本是melodic，在运行6.2.4的launch文件的时候遇到下面这个报错
![2020-05-31 17-44-49 的屏幕截图](https://user-images.githubusercontent.com/48182501/83349305-74376300-a366-11ea-9917-c853cf6f51dc.png)
rviz打开后缺少两边的轮子
![2020-05-31 17-46-14 的屏幕截图](https://user-images.githubusercontent.com/48182501/83349323-a5b02e80-a366-11ea-99c7-4fb676a7a6cc.png)
并且有这样的报错
![2020-05-31 17-46-59 的屏幕截图](https://user-images.githubusercontent.com/48182501/83349340-c37d9380-a366-11ea-8fa3-9a836aab6c41.png)
按网上的方法也试过了sudo apt-get install ros-melodic-joint-state-publisher-gui，但是没有效果，请问可能是哪里出了问题？

**Comment by huchunxu** [comment]
把launch文件中的joint_state_publisher都改为joint_state_publisher_gui试一下，原来joint_state_publisher这个节点可以不用了



huchunxu@ps-micro.com
 
发件人： hhxzzy
发送时间： 2020-05-31 17:52
收件人： huchunxu/ros_exploring
抄送： Subscribed
主题： [huchunxu/ros_exploring] 6.2.4运行launch文件报错[joint_state_publisher-2] process has died (#24)
古月老师你好，我的ubuntu版本是18.04，ros版本是melodic，在运行6.2.4的launch文件的时候遇到下面这个报错

rviz打开后缺少两边的轮子

并且有这样的报错

按网上的方法也试过了sudo apt-get install ros-melodic-joint-state-publisher-gui，但是没有效果，请问可能是哪里出了问题？
―

**Comment by hhxzzy** [comment]
发现报错里有这几句
![2020-05-31 23-43-09 的屏幕截图](https://user-images.githubusercontent.com/48182501/83356402-8b8f4400-a398-11ea-822d-68a84b442881.png)
用sudo apt install ros-melodic-joint-state-publisher可以解决问题！
谢谢古月解答！
