### ISSUE TITLE
有关于功能包的一些问题

### ISSUE THREAD

**Issue by Dullyter** [huchunxu/ros_exploring#25]
古月老师，你好，请问你《ros机器人开发实践》的源码，也就是ros_exploring中有好几个文件夹，以robot_mrobot为例，它包含好几个功能包，像mrobot_bringup、mrobot_description这些的，那我把你的源码复制到我工作空间的src文件夹中，是应该把mrobot_bringup、mrobot_description这些功能包一个个复制过来，还是说我直接复制robot_mrobot这个文件夹就行

**Comment by ross114** [comment]
you can just copy the whole package in the workspace
