### ISSUE TITLE
catkin build melodic版本 失败

### ISSUE THREAD

**Issue by ZhangDonglin12** [huchunxu/ros_exploring#28]
相关依赖无法编译
![image](https://user-images.githubusercontent.com/46352470/106862734-7d9d7a00-6702-11eb-950b-22dd4d884cfd.png)

**Comment by huchunxu** [comment]
可以使用catkin_make编译

**Comment by bufeng-12** [comment]
您好！我已收到你的邮件！谢谢！          ——曾君
