### ISSUE TITLE
A problem about navigation

### ISSUE THREAD

**Issue by zshzdt** [huchunxu/ros_exploring#29]
Hi ,I run the code of mrobot_navigation, when I give the 2D Nav Goal, robot won't move as the green path,instead, it moves irregular, and it seems that it won't arrive the goal, so I am wanderring why? Is it normal? 
Thank you

**Comment by huchunxu** [comment]
If it's ROS Melodic, please use melodic branch. The motion direction of differential controller plugin is opposite.

**Comment by Julius-ZCJ** [comment]
@zshzdt 
I get this problem also, this problem due to xacro file set wrong, you just modify mrobot_body.urdf.xacro line 257 and 258 like picture
![Screenshot 2021-11-04 02:23:03](https://user-images.githubusercontent.com/42171296/140267993-5e9f5164-52a8-4bc2-ad8a-db3ba3582cb7.png)
:
