### ISSUE TITLE
《ROS机器人开发实践》阅读过程发现的笔误

### ISSUE THREAD

**Issue by WXLmjr** [huchunxu/ros_exploring#3]
原书485页
14.25.节
倒数第二行的“catikin”拼写有误，多了一个字母“i”.

**Comment by huchunxu** [comment]
收到，感谢

**Comment by jinhuan-hit** [comment]
原书122页
6.2.3节
上面文字：需要把圆柱体围绕x轴旋转90度（使用弧度表示大约为0.75），个人感觉弧度值应该改为1.57。

**Comment by huchunxu** [comment]
> 原书122页
> 6.2.3节
> 上面文字：需要把圆柱体围绕x轴旋转90度（使用弧度表示大约为0.75），个人感觉弧度值应该改为1.57。

此处确实是笔误，在最新的印刷版中已经修正，非常感谢

**Comment by huchunxu** [comment]
> 原书122页
> 6.2.3节
> 上面文字：需要把圆柱体围绕x轴旋转90度（使用弧度表示大约为0.75），个人感觉弧度值应该改为1.57。

此处确实是笔误，在最新的印刷版中已经修正，非常感谢

**Comment by jinhuan-hit** [comment]
原书132页
6.4.3节
运行以下命令，即可看到安装有激光雷达的机器人模型（见图6-12）：
roslaunch mrobot_description display_mrobot_with_rplidar.launch
下载github的源码，mrobot_description包里面的launch文件名为display_mrobot_with_laser.launch。

**Comment by huchunxu** [comment]
> 原书132页
> 6.4.3节
> 运行以下命令，即可看到安装有激光雷达的机器人模型（见图6-12）：
> roslaunch mrobot_description display_mrobot_with_rplidar.launch
> 下载github的源码，mrobot_description包里面的launch文件名为display_mrobot_with_laser.launch。

非常感谢，已记录
