### ISSUE TITLE
gazebo仿真中无法使用键盘控制小车移动

### ISSUE THREAD

**Issue by Julius-ZCJ** [huchunxu/ros_exploring#31]
胡老师您好：
        我刚刚开始学习ros机器人，现在我仿照您写的ros机器人开发上的案例写了一个urdf小车描述文件，在加载进gazebo是正常的，但是我启用键盘控制，我发现小车不会动，这是什么问题阿。
以下是我的xacro文件内容：
`
<xacro:macro name="sphere_inertial_matrix" params="m r">
        <inertial>
            <mass value="${m}" />
            <inertia ixx="${2*m*r*r/5}" ixy="0" ixz="0"
                iyy="${2*m*r*r/5}" iyz="0" 
                izz="${2*m*r*r/5}" />
        </inertial>
    </xacro:macro>

    <xacro:macro name="cylinder_inertial_matrix" params="m r h">
        <inertial>
            <mass value="${m}" />
            <inertia ixx="${m*(3*r*r+h*h)/12}" ixy = "0" ixz = "0"
                iyy="${m*(3*r*r+h*h)/12}" iyz = "0"
                izz="${m*r*r/2}" /> 
        </inertial>
    </xacro:macro>

    <xacro:macro name="box_inertial_matrix" params="m w h d">
        <inertial>
            <mass value="${m}" />
            <inertia ixx="${m*(h*h+d*d)/12}" ixy = "0" ixz = "0"
                iyy="${m*(w*w+d*d)/12}" iyz = "0"
                izz="${m*(w*w+h*h)/12}" /> 
        </inertial>
    </xacro:macro>

    <xacro:macro name="wheel" params="prefix reflect parent_link">
        <joint name="${prefix}_wheel_joint" type="continuous">
            <origin xyz="-1.012 ${reflect*wheel_joint_y} 0.04" rpy="0 0 0"/>
            <parent link="${parent_link}"/>
            <child link="${prefix}_wheel_link"/>
            <axis xyz="0 1 0"/>
        </joint>

        <link name="${prefix}_wheel_link">

            <visual>
                <origin xyz="0 0 0" rpy="${M_PI/2} 0 0"/>
                <geometry>
                    <cylinder length="0.08" radius="0.04" />
                </geometry>
                <material name="gray"/>
            </visual>

            <collision>
                <origin xyz="0 0 0" rpy="${M_PI/2} 0 0"/>
                <geometry>
                    <cylinder length="0.08" radius="0.04" />
                </geometry>
            </collision>
            <cylinder_inertial_matrix  m="0.1" r="0.04" h="0.08" />
        </link>
        <gazebo reference="${prefix}_wheel_link">
            <material>Gazebo/Gray</material>
        </gazebo>

        
        <transmission name="${prefix}_wheel_trans">
            <type>transmission_interface/SimpleTransmission</type>
            <joint name="${prefix}_wheel_joint" />
            <actuator name="${prefix}_wheel_joint_motor">
                <hardwareInterface>VelocityJointInterface</hardwareInterface>  
                <mechanicalReduction>1</mechanicalReduction>
            </actuator>
        </transmission>

    </xacro:macro>

    
    <xacro:macro name="caster" params="prefix reflect parent_link">
        <joint name="${prefix}_caster_joint" type="continuous">
            <origin xyz="-0.0671 ${reflect*caster_joint_y} 0.08" rpy="0 0 0"/>
            <parent link="${parent_link}"/>
            <child link="${prefix}_caster_link"/>
            <axis xyz="0 1 0"/>
        </joint>

        <link name="${prefix}_caster_link">

            <visual>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <sphere radius="0.08" />
                </geometry>
                <material name="gray"/>
            </visual>

            <collision>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <sphere radius="0.08" />
                </geometry>
            </collision>
            <sphere_inertial_matrix  m="0.1" r="0.08" />
        </link>

        <gazebo reference="${prefix}_caster_link">
            <material>Gazebo/Gray</material>
        </gazebo>

    </xacro:macro>`

下面是我执行命令rostopic info /cmd_vel的结果：
`
Type: geometry_msgs/Twist

Publishers: None

Subscribers: 
 * /gazebo (http://localhost:38097/)
`
当启动键盘控制命令roslaunch mrobot_teleop mrobot_teleop.launch的结果：
`Type: geometry_msgs/Twist

Publishers: 
 * /mrobot_teleop (http://localhost:42235/)

Subscribers: 
 * /gazebo (http://localhost:38097/)

`
我想请教下我该怎么改才能正确使用键盘控制小车呢？

还有就是我想请问下有什么值的推荐的ros学习论坛么么？目前遇到问题都不知道去哪里提问。

**Comment by Julius-ZCJ** [comment]
忘记说了，我是在ubuntu18.04上，使用的ros版本是melodic。

下面是我的gazebo的插件的设置
` 
        <gazebo>
            <plugin name="differential_drive_controller" filename="libgazebo_ros_diff_drive.so">
                <rosDebugLevel>Debug</rosDebugLevel>
                <publishWheelTF>true</publishWheelTF>
                <robotNamespace>/</robotNamespace>
                <publishTf>1</publishTf>
                <publishWheelJointState>true</publishWheelJointState>
                <alwaysOn>true</alwaysOn>
                <updateRate>100.0</updateRate>
                <legacyMode>true</legacyMode>
                <leftJoint>left_wheel_joint</leftJoint>
                <rightJoint>right_wheel_joint</rightJoint>
                <wheelSeparation>${wheel_joint_y*2}</wheelSeparation>
                <wheelDiameter>0.08</wheelDiameter>
                <broadcastTF>1</broadcastTF>
                <wheelTorque>30</wheelTorque>
                <wheelAcceleration>1</wheelAcceleration>
                <commandTopic>cmd_vel</commandTopic>
                <odometryFrame>odom</odometryFrame> 
                <odometryTopic>odom</odometryTopic> 
                <robotBaseFrame>base_footprint</robotBaseFrame>
            </plugin>
        </gazebo>`

**Comment by Julius-ZCJ** [comment]
老师，我通过rviz发现，轮子是会会转动的，但是整个小车的模型不会移动，感觉好奇怪阿

**Comment by Julius-ZCJ** [comment]
urdf文件参数设置问题，将动力轮的mass调大可以解决，不知道什么原理

**Comment by quickpig** [comment]
如果调大mass就能解决的话，那原理一定是你设置的轮子质量太小，而小车质量太大，导致摩擦力不足以让车动

**Comment by bufeng-12** [comment]
您好！我已收到你的邮件！谢谢！          ——曾君
