### ISSUE TITLE
cartographer建图中小车和雷达分离了

### ISSUE THREAD

**Issue by Julius-ZCJ** [huchunxu/ros_exploring#34]
胡老师你好
我在学习第9章cartographer中，在安装好cartographer后，测试museum的demo正常，但是在本章中的建图程序时出现了建图中rviz中的雷达和车身分离了，但是gazebo中的还是正常的，如下图所示：
![9db69ebc203521c8a021b194aea8637](https://user-images.githubusercontent.com/42171296/138425549-7dfb4974-f7bd-4c49-8db7-6fb9182dd118.jpg)
![162934725478d261d92b1a04aab81f7](https://user-images.githubusercontent.com/42171296/138425582-0935f4e3-6469-45cc-a63b-971f163bb01b.jpg)

我想问下这是什么原因导致的，该怎么解决呢？
我的环境时ubuntu18.04，ros是melodic

**Comment by DandyLorenz** [comment]
速度调慢点试下，我的没啥问题。我的是16.04的
