### ISSUE TITLE
导航中遇到的问题

### ISSUE THREAD

**Issue by Julius-ZCJ** [huchunxu/ros_exploring#35]
胡老师你好
    我在学习9.10.2章中的gazebo仿真导航中遇到了两个问题：
1. 我发现仿真导航中绿色的导航线不是一次性画出来的，而是慢慢延伸出来的，这个是否正常
2. 我发现导航过程中雷达出现漂移的现象，就是原本是没有障碍物的地方也会出现红色雷达线条，这个是什么原因造成的
从下图中可以清楚的看到：
![Screenshot 2021-11-04 03:01:56](https://user-images.githubusercontent.com/42171296/140272156-48fcce37-ff3c-4352-a53b-8f8caac74e81.png)

**Comment by DandyLorenz** [comment]
兄弟，加个QQ交流下，我也刚好学到这，有些坑可以交流下。我qq:1213126651。备注：ROS交流
