### ISSUE TITLE
导航中局部规划路径出现混乱

### ISSUE THREAD

**Issue by Julius-ZCJ** [huchunxu/ros_exploring#36]
胡老师您好：
       我在学习和实践导航算法过程中发现局部路径规划有时候会出现混乱，如下图所示，这是什么原因导致的呢？怎么做可以缓解或者解决这个问题？
![problem1](https://user-images.githubusercontent.com/42171296/141223906-ee92b6bb-95a3-4004-89f0-6e2f7af5a3a3.png)

**Comment by DandyLorenz** [comment]
兄弟，加个QQ交流下，我也刚好学到这，有些坑可以交流下。我qq:1213126651。备注：ROS交流

**Comment by Hwm-china** [comment]
兄弟这个解决问题了吗
