### ISSUE TITLE
when i run "roslaunch mrobot_gazebo view_mrobot_gazebo.launch " .There is no robot model appears in gazebo (my ROS version is noetic)

### ISSUE THREAD

**Issue by Lansher** [huchunxu/ros_exploring#38]
![isn't appear model in gazebo](https://user-images.githubusercontent.com/68136467/144179119-546eb97c-be65-4c5a-ac0e-3af3e00bd084.png)

roslaunch mrobot_gazebo view_mrobot_gazebo.launch 
... logging to /home/lansher/.ros/log/289feef6-5267-11ec-b666-bfd761c8268d/roslaunch-lansher-42369.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

xacro: in-order processing became default in ROS Melodic. You can drop the option.
started roslaunch server http://lansher:44513/

SUMMARY
========

PARAMETERS
 * /gazebo/enable_ros_network: True
 * /robot_description: <?xml version="1....
 * /robot_state_publisher/publish_frequency: 50.0
 * /rosdistro: noetic
 * /rosversion: 1.15.13
 * /use_sim_time: False

NODES
  /
    gazebo (gazebo_ros/gzserver)
    gazebo_gui (gazebo_ros/gzclient)
    joint_state_publisher (joint_state_publisher/joint_state_publisher)
    robot_state_publisher (robot_state_publisher/robot_state_publisher)
    urdf_spawner (gazebo_ros/spawn_model)

ROS_MASTER_URI=http://localhost:11311

process[gazebo-1]: started with pid [42385]
process[gazebo_gui-2]: started with pid [42389]
process[joint_state_publisher-3]: started with pid [42395]
process[robot_state_publisher-4]: started with pid [42396]
process[urdf_spawner-5]: started with pid [42397]
[ WARN] [1638337379.958729611]: Shutdown request received.
[ WARN] [1638337379.958785104]: Reason given for shutdown: [[/robot_state_publisher] Reason: new node registered with same name]
[ WARN] [1638337379.961768081]: link 'base_link' material 'yellow' undefined.
[ WARN] [1638337379.963353600]: link 'base_link' material 'yellow' undefined.
[INFO] [1638337380.393707]: Loading model XML from ros parameter robot_description
[INFO] [1638337380.399691]: Waiting for service /gazebo/spawn_urdf_model
[WARN] [1638337380.403952]: wait_for_service(/gazebo/spawn_urdf_model): failed to contact, will keep trying
[ INFO] [1638337380.563418959]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
[ INFO] [1638337380.565506077]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1638337380.634588913]: waitForService: Service [/gazebo_gui/set_physics_properties] has not been advertised, waiting...
[ INFO] [1638337380.636105684]: Finished loading Gazebo ROS API Plugin.
[INFO] [1638337381.010323]: wait_for_service(/gazebo/spawn_urdf_model): finally were able to contact [rosrpc://lansher:51887]
[INFO] [1638337381.013769]: Calling service /gazebo/spawn_urdf_model
[ INFO] [1638337381.045061249]: waitForService: Service [/gazebo/set_physics_properties] is now available.

libcurl: (5) Could not resolve proxy: http
[INFO] [1638337381.216835]: Spawn status: SpawnModel: Successfully spawned entity
[ INFO] [1638337381.230930738]: Physics dynamic reconfigure ready.
[ INFO] [1638337381.240718709]: Starting plugin DiffDrive(ns = //)
[ INFO] [1638337381.241129999]: DiffDrive(ns = //): <rosDebugLevel> = Debug
[ INFO] [1638337381.242247061]: DiffDrive(ns = //): <tf_prefix> = 
[DEBUG] [1638337381.242596085]: DiffDrive(ns = //): <commandTopic> = cmd_vel
[DEBUG] [1638337381.242618036]: DiffDrive(ns = //): <odometryTopic> = odom
[DEBUG] [1638337381.242630840]: DiffDrive(ns = //): <odometryFrame> = odom
[DEBUG] [1638337381.242644636]: DiffDrive(ns = //): <robotBaseFrame> = base_footprint
[DEBUG] [1638337381.242714316]: DiffDrive(ns = //): <publishWheelTF> = true
[ WARN] [1638337381.242732851]: DiffDrive(ns = //): missing <publishOdomTF> default is true
[DEBUG] [1638337381.242759431]: DiffDrive(ns = //): <publishWheelJointState> = true
[DEBUG] [1638337381.243152116]: DiffDrive(ns = //): <wheelSeparation> = 0.26000000000000001
[DEBUG] [1638337381.243181581]: DiffDrive(ns = //): <wheelDiameter> = 0.066000000000000003
[DEBUG] [1638337381.243204364]: DiffDrive(ns = //): <wheelAcceleration> = 1.8
[DEBUG] [1638337381.243227327]: DiffDrive(ns = //): <wheelTorque> = 30
[DEBUG] [1638337381.243246693]: DiffDrive(ns = //): <updateRate> = 100
[ WARN] [1638337381.243931035]: DiffDrive(ns = //): missing <odometrySource> default is 1
[DEBUG] [1638337381.244192014]: DiffDrive(ns = //): <leftJoint> = base_to_wheel_left_joint

**Comment by frischzenger** [comment]
你这个问题解决了没？
