### ISSUE TITLE
kinect 驱动问题

### ISSUE THREAD

**Issue by guan4286** [huchunxu/ros_exploring#4]
g@g-system-product-name:~/SensorKinect/Bin$ cd Sensor-Bin-Linux-x64-v5.1.2.1/
g@g-system-product-name:~/SensorKinect/Bin/Sensor-Bin-Linux-x64-v5.1.2.1$ ls
Bin  Config  GPL.txt  Install  install.sh  LGPL.txt  Lib
g@g-system-product-name:~/SensorKinect/Bin/Sensor-Bin-Linux-x64-v5.1.2.1$ ls Install/
55-primesense-usb.rules  blacklist-gspca-kinect.conf
g@g-system-product-name:~/SensorKinect/Bin/Sensor-Bin-Linux-x64-v5.1.2.1$ sudo ./install.sh 
[sudo] password for g: 
Installing PrimeSense Sensor
****************************

creating config dir /usr/etc/primesense...OK
copying shared libraries...OK
copying executables...OK
registering module 'libXnDeviceSensorV2KM.so' with OpenNI...OK
registering module 'libXnDeviceFile.so' with OpenNI...OK
copying server config file...OK
setting uid of server...OK
creating server logs dir...OK
installing usb rules...OK
installing modprobe blacklist...OK

*** DONE ***

我的系统是ubuntu 16.04 安装驱动显示也成功　但是为什么还是显示没有设备连接呢？

Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://g-system-product-name:43641/

SUMMARY
========

PARAMETERS
 * /camera/camera_nodelet_manager/num_worker_threads: 4
 * /camera/depth_registered_rectify_depth/interpolation: 0
 * /camera/driver/data_skip: 0
 * /camera/driver/debug: False
 * /camera/driver/depth_camera_info_url: 
 * /camera/driver/depth_frame_id: camera_depth_opti...
 * /camera/driver/depth_registration: True
 * /camera/driver/device_id: #1
 * /camera/driver/diagnostics_max_frequency: 30.0
 * /camera/driver/diagnostics_min_frequency: 30.0
 * /camera/driver/diagnostics_tolerance: 0.05
 * /camera/driver/diagnostics_window_time: 5.0
 * /camera/driver/enable_depth_diagnostics: False
 * /camera/driver/enable_ir_diagnostics: False
 * /camera/driver/enable_rgb_diagnostics: False
 * /camera/driver/rgb_camera_info_url: 
 * /camera/driver/rgb_frame_id: camera_rgb_optica...
 * /rosdistro: kinetic
 * /rosversion: 1.12.14

NODES
  /camera/
    camera_nodelet_manager (nodelet/nodelet)
    depth_registered_hw_metric_rect (nodelet/nodelet)
    depth_registered_metric (nodelet/nodelet)
    depth_registered_rectify_depth (nodelet/nodelet)
    driver (nodelet/nodelet)
    points_xyzrgb_hw_registered (nodelet/nodelet)
    rgb_debayer (nodelet/nodelet)
    rgb_rectify_color (nodelet/nodelet)
    rgb_rectify_mono (nodelet/nodelet)

auto-starting new master
process[master]: started with pid [5494]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to c6dc6758-ca0b-11e8-b46b-2cfda1bc2526
process[rosout-1]: started with pid [5507]
started core service [/rosout]
process[camera/camera_nodelet_manager-2]: started with pid [5524]
process[camera/driver-3]: started with pid [5525]
process[camera/rgb_debayer-4]: started with pid [5526]
process[camera/rgb_rectify_mono-5]: started with pid [5527]
process[camera/rgb_rectify_color-6]: started with pid [5536]
process[camera/depth_registered_rectify_depth-7]: started with pid [5557]
process[camera/points_xyzrgb_hw_registered-8]: started with pid [5567]
process[camera/depth_registered_hw_metric_rect-9]: started with pid [5583]
process[camera/depth_registered_metric-10]: started with pid [5592]
[ INFO] [1538901257.110013562]: Initializing nodelet with 4 worker threads.
[ INFO] [1538901257.211923164]: No devices connected.... waiting for devices to be connected
[ INFO] [1538901260.212137123]: No devices connected.... waiting for devices to be connected
[ INFO] [1538901263.212348427]: No devices connected.... waiting for devices to be connected
[ INFO] [1538901266.212569534]: No devices connected.... waiting for devices to be connected

**Comment by guan4286** [comment]
这要怎么解决呢或者可能是什么问题呢？

**Comment by huchunxu** [comment]
应该是驱动的问题
