### ISSUE TITLE
TF_REPEATED_DATA

### ISSUE THREAD

**Issue by Wang-Minxin** [huchunxu/ros_exploring#40]
胡老师，您好。我的系统是Ubuntu 20.04 + noetic版本，在执行如下两条命令时
1. roslaunch mrobot_gazebo mrobot_laser_nav_gazebo.launch
2. roslaunch mrobot_navigation nav_demo.launch 
出现如下错误，在rviz中机器人无法定位。
Warning: TF_REPEATED_DATA ignoring data with redundant timestamp for frame wheel_right_link at time 474.383000 according to authority unknown_publisher
         at line 278 in /tmp/binarydeb/ros-noetic-tf2-0.7.5/src/buffer_core.cpp
Warning: TF_REPEATED_DATA ignoring data with redundant timestamp for frame wheel_left_link at time 474.413000 according to authority unknown_publisher
         at line 278 in /tmp/binarydeb/ros-noetic-tf2-0.7.5/src/buffer_core.cpp
Warning: TF_REPEATED_DATA ignoring data with redundant timestamp for frame wheel_right_link at time 474.413000 according to authority unknown_publisher
         at line 278 in /tmp/binarydeb/ros-noetic-tf2-0.7.5/src/buffer_core.cpp
Warning: TF_REPEATED_DATA ignoring data with redundant timestamp for frame wheel_left_link at time 474.413000 according to authority unknown_publisher
         at line 278 in /tmp/binarydeb/ros-noetic-tf2-0.7.5/src/buffer_core.cpp
Warning: TF_REPEATED_DATA ignoring data with redundant timestamp for frame wheel_right_link at time 474.413000 according to authority unknown_publisher
         at line 278 in /tmp/binarydeb/ros-noetic-tf2-0.7.5/src/buffer_core.cpp

**Comment by Wang-Minxin** [comment]
![2021-12-29 22-11-09屏幕截图](https://user-images.githubusercontent.com/57715105/147671257-da4c802f-3628-4577-85ce-ce23a8e62c25.png)

**Comment by Wang-Minxin** [comment]
关闭gazebo中的use_sim_time可以成功定位，但是会接受不到雷达数据，路径规划失败。

**Comment by YanzhaoDrew** [comment]
I have the some question, I don't know how to solve it. If you know the solution, please tell me.
