### ISSUE TITLE
改用python3 的相关问题ModuleNotFoundError: No module named 'ax12'

### ISSUE THREAD

**Issue by guan4286** [huchunxu/ros_exploring#6]
这个问题怎么解决呢。 ax12是您自定义的模块吗？

**Comment by guan4286** [comment]
没人维护吗？

**Comment by guan4286** [comment]
SUMMARY
========

PARAMETERS
 * /arbotix/controllers/base_controller/Kd: 12
 * /arbotix/controllers/base_controller/Ki: 0
 * /arbotix/controllers/base_controller/Ko: 50
 * /arbotix/controllers/base_controller/Kp: 12
 * /arbotix/controllers/base_controller/accel_limit: 1.0
 * /arbotix/controllers/base_controller/base_frame_id: base_footprint
 * /arbotix/controllers/base_controller/base_width: 0.26
 * /arbotix/controllers/base_controller/ticks_meter: 4100
 * /arbotix/controllers/base_controller/type: diff_controller
 * /arbotix/sim: True
 * /robot_description: <?xml version="1....
 * /robot_state_publisher/publish_frequency: 20.0
 * /rosdistro: kinetic
 * /rosversion: 1.12.14
 * /use_gui: False
 * /use_sim_time: False

NODES
  /
    arbotix (arbotix_python/arbotix_driver)
    joint_state_publisher (joint_state_publisher/joint_state_publisher)
    robot_state_publisher (robot_state_publisher/robot_state_publisher)
    rviz (rviz/rviz)

auto-starting new master
process[master]: started with pid [10567]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 0767860a-efe0-11e8-a5fc-2cfda1bc2526
process[rosout-1]: started with pid [10580]
started core service [/rosout]
process[arbotix-2]: started with pid [10598]
process[joint_state_publisher-3]: started with pid [10599]
process[robot_state_publisher-4]: started with pid [10600]
process[rviz-5]: started with pid [10601]
Traceback (most recent call last):
  File "/home/g/catkin_ws/src/arbotix_ros/arbotix_python/bin/arbotix_driver", line 36, in <module>
    from arbotix_python.arbotix import ArbotiX, ArbotiXException
  File "/home/g/catkin_ws/src/arbotix_ros/arbotix_python/src/arbotix_python/arbotix.py", line 34, in <module>
    from ax12 import *
ModuleNotFoundError: No module named 'ax12'
[arbotix-2] process has died [pid 10598, exit code 1, cmd /home/g/catkin_ws/src/arbotix_ros/arbotix_python/bin/arbotix_driver __name:=arbotix __log:=/home/g/.ros/log/0767860a-efe0-11e8-a5fc-2cfda1bc2526/arbotix-2.log].
log file: /home/g/.ros/log/0767860a-efe0-11e8-a5fc-2cfda1bc2526/arbotix-2*.log
================================================================================REQUIRED process [rviz-5] has died!
process has finished cleanly
log file: /home/g/.ros/log/0767860a-efe0-11e8-a5fc-2cfda1bc2526/rviz-5*.log
Initiating shutdown!
================================================================================
[rviz-5] killing on exit
[joint_state_publisher-3] killing on exit
[robot_state_publisher-4] killing on exit
[rosout-1] killing on exit
[master] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete
done

**Comment by huchunxu** [comment]
不是我写的，arbotix本身是一个独立的包，需要apt安装或者源码下载编译安装
