### ISSUE TITLE
rosbag: error: Cannot find rosbag/play executable

### ISSUE THREAD

**Issue by guan4286** [huchunxu/ros_exploring#7]
g@g:~$ rosbag play rgbd_dataset_freiburg1_desk.bag 
Usage: rosbag play BAGFILE1 [BAGFILE2 BAGFILE3 ...]

rosbag: error: Cannot find rosbag/play executable

**Comment by guan4286** [comment]
how to solve this problem

**Comment by huchunxu** [comment]
install rosbag or source setup.bash
