### ISSUE TITLE
moveit and gazebo

### ISSUE THREAD

**Issue by TXLszu** [huchunxu/ros_exploring#8]
胡老师您好，我在本书第10.12.4章节中，运行Moveit和Gazebo的launch文件
$ roslaunch marm_gazebo  arm_bringup_moveit.launch 时出现了问题，想请教您一下？
运行时gazebo和rviz都能正常启动，使用moveit进行规划时，只有rviz中的机械臂可以运动，gazebo中的机械臂不能一起运动，出现下面的错误是什么原因呢？
[ERROR] [1543648302.946867035, 54.954000000]: Unable to identify any set of controllers that can actuate the specified joints: [ joint1 joint2 joint3 joint4 joint5 joint6 ]
[ERROR] [1543648302.946922001, 54.954000000]: Known controllers and their joints:

[ERROR] [1543648302.946988980, 54.954000000]: Apparently trajectory initialization failed

**Comment by WeidiDeng** [comment]
rosed marm_moveit_config arm_moveit_controller_manager.launch.xml
把rosparam那一行的controllers.yaml改成controllers_gazebo.yaml.
